

# :schedule:
#   CheckPaid:
#     cron: '1 * * * * *'   # Runs once per hour
#     class: CheckPaid
#     quene: schedule
#     enabled: true

# clear_leaderboards_contributors:
#   cron: '1 * * * * *'
#   class: CheckEveryPaidJob
#   queue: low
#   args: contributors
#   description: 'This job resets the weekly leaderboard for contributions'

clear_leaderboards_contributors:
  class: CheckEveryPaidJob
  queue: low
  every: '30m'